# Generated by Django 4.2.11 on 2024-03-15 10:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_alter_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='average_score',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
    ]
