# Generated by Django 4.2.11 on 2024-03-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_team_average_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
